name: enfora
label: Enfora Gateway
overview_uri: /enfora
device_uri: /enfora/command_request/list
device_class: Enfora::Device

development:
  adapter: mysql
  database: enfora_enfora
  username: root
  password: 
  host: localhost

production:
  adapter: mysql
  database: enfora_enfora
  username: root
  password: 
  host: localhost

#production:
#  adapter: mysql
#  database: enfora_prod
#  username: root
#  password: rootpass
#  host: localhost